[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "faster-whisper>=1.2.0",
    "openai>=1.99.1",
    "pandas>=2.3.1",
    "pydub>=0.25.1",
    "streamlit>=1.48.0",
]
